export const mockTeamMembers = [
  {
    id: "1",
    name: "Dagana Lois",
    email: "daganalo@gmail.com",
    phone: "+2345678098",
    location: "Abuja, Nigeria",
    role: "Admin",
    languages: ["English", "Hausa", "Igbo"],
    coverageAreas: ["Politics", "Insurgency"],
  },
  {
    id: "2",
    name: "Dagana Lois",
    email: "daganalo@gmail.com",
    phone: "+2345678098",
    location: "Abuja, Nigeria",
    role: "User",
    languages: ["English", "Hausa", "Igbo"],
    coverageAreas: ["Politics", "Insurgency"],
  },
  {
    id: "3",
    name: "Dagana Lois",
    email: "daganalo@gmail.com",
    phone: "+2345678098",
    location: "Abuja, Nigeria",
    role: "User",
    languages: ["English", "Hausa", "Igbo"],
    coverageAreas: ["Politics", "Insurgency"],
  },
  {
    id: "4",
    name: "Dagana Lois",
    email: "daganalo@gmail.com",
    phone: "+2345678098",
    location: "Abuja, Nigeria",
    role: "User",
    languages: ["English", "Hausa", "Igbo"],
    coverageAreas: ["Politics", "Insurgency"],
  },
  {
    id: "5",
    name: "Dagana Lois",
    email: "daganalo@gmail.com",
    phone: "+2345678098",
    location: "Abuja, Nigeria",
    role: "User",
    languages: ["English", "Hausa", "Igbo"],
    coverageAreas: ["Politics", "Insurgency"],
  },
  {
    id: "6",
    name: "Dagana Lois",
    email: "daganalo@gmail.com",
    phone: "+2345678098",
    location: "Abuja, Nigeria",
    role: "User",
    languages: ["English", "Hausa", "Igbo"],
    coverageAreas: ["Politics", "Insurgency"],
  },
  {
    id: "7",
    name: "Dagana Lois",
    email: "daganalo@gmail.com",
    phone: "+2345678098",
    location: "Abuja, Nigeria",
    role: "User",
    languages: ["English", "Hausa", "Igbo"],
    coverageAreas: ["Politics", "Insurgency"],
  },
]